spring.application.name: learner-node
server.port: 8810

cluster:
  kafka:
    bootstrap-servers: localhost:9093
    topic: kafka_topic
    groupId: command-log-learner-group

learner:
  bufferSize: 1024
  pollInterval: 100
  maxSnapshotCheckCircles: 50
  snapshotFragmentSize: 100000
  snapshotLifeTime: 20

spring.datasource:
  url: jdbc:mysql://localhost:3306/p2pc
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  open-in-view: false
  hibernate.ddl-auto: none
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
