spring.application.name: learner-node
server.port: 8810

cluster:
  kafka:
    bootstrap-servers: localhost:9093
    topic: kafka_topic
    groupId: command-log-learner-group

learner:
  bufferSize: 2048
  pollInterval: 100
  maxSnapshotCheckCircles: 50
  snapshotFragmentSize: 100000
  snapshotLifeTime: 10

spring.datasource:
  url: jdbc:postgresql://localhost:5432/p2pc
  username: admin
  password: admin
  driver-class-name: org.postgresql.Driver

spring.jpa:
  open-in-view: false
  hibernate.ddl-auto: none
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
