server:
  port: 8081
  grpc:
    port: 9090

cluster:
  kafka:
    bootstrap-servers: localhost:9093
    topic: kafka_topic
    groupId: command-log-leader-group

spring.datasource:
  url: jdbc:mysql://localhost:3306/p2pc
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  open-in-view: false
  hibernate.ddl-auto: none
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
---
leader:
  commandBufferPow: 18
  replyBufferPow: 19
  logsChunkSize: 1000